nodeLinker: node-modules

npmScopes:
  hanxven:
    npmAuthToken: "${NODE_AUTH_TOKEN}"
    npmRegistryServer: "https://npm.pkg.github.com"
  leaguetavern:
    npmAuthToken: "${NODE_AUTH_TOKEN}"
    npmRegistryServer: "https://npm.pkg.github.com"

yarnPath: .yarn/releases/yarn-4.9.1.cjs
